service: alexa-list-sync

frameworkVersion: '2'

custom:
  secrets: ${file(secrets.json)}
  pythonRequirements:
     dockerizePip: non-linux
provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

  region: ${self:custom.secrets.REGION, 'us-east-1'}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${self:custom.secrets.airtableKeyName}'

  environment:
    paramNameAirtable: ${self:custom.secrets.airtableKeyName}
    airtableBaseId: ${self:custom.secrets.airtableBaseId}
    airtableTableName: ${self:custom.secrets.airtableTableName}
    airtableListView: ${self:custom.secrets.airtableListView}
    airtableAllView: ${self:custom.secrets.airtableAllView}

plugins:
   - serverless-python-requirements

package:
  exclude:
    - img/**

functions:
  item-added:
    handler: alexa-list.item_added
    events:
      - http:
          path: added
          method: post
          cors: true
  item-removed:
    handler: alexa-list.item_removed
    events:
      - http:
          path: removed
          method: post
          cors: true
  print-list:
    handler: print-list.print_list
    events:
      - http:
          path: print
          method: get
          cors: true
