service: alexa-list-sync

frameworkVersion: '2'

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

  region: ${self:custom.secrets.REGION, 'us-east-1'}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${self:custom.secrets.airtableKeyARN}'


package:
  exclude:
    - img/**

functions:
  item-added:
    handler: alexa-list.item_added
    events:
      - http:
          path: added
          method: post
          cors: true
  item-removed:
    handler: alexa-list.item_removed
    events:
      - http:
          path: removed
          method: post
          cors: true
  print-list:
    handler: print-list.print_list
    events:
      - http:
          path: print
          method: get
          cors: true